### PR TITLE
Complete refactor

### PR DESCRIPTION
**Pull request by Keats**
This allows #10 in a basic but effective way: the `validator` crate exposes a `ValidationError` and `ValidationErrors`.

`ValidationError` is identical with the one with the same name in Django (code, message and params) and `ValidationErrors` is just a HashMap<FieldName, Vec<ValidationError>>.

In addition to the current validation parameters, each validator now allows to set a `code` and a `message` directly from the attribute. For example:

```rust
#[derive(Debug, Validate)]
struct TestStruct {
    #[validate(regex(path = "RE2", code = "oops"))]
    val: String,
}

#[derive(Debug, Validate)]
struct TestStruct {
    #[validate(email(message = "oops"))]
    val: String,
}
```

The `params` will automatically be filled for each field validation with:

- the `value` of the field
- the parameters to the validator, when it make sense (eg path to a function or regex are useless to write an error message). For example the `range` validator will always have 3 params: `value`, `min` and `max`

Most of the `String` types have been switched to `Cow<'static, str>` as well (#20) 

Things left to think about:

- don't use serde_json: find a cross data format way to store them in the struct
- bikeshedding on the attributes names (https://github.com/Keats/validator/blob/revamp/validator_derive/src/lib.rs#L317-L331)
- renaming Custom validator to Function? more bikeshedding basically
- Use a trait instead of a struct for ValidationError? (see #10)
- How to extract serde serialization errors? (#22)

### CODE REVIEW

**Comment by Keats** [comment]
@theduke @alexander-irbis @Leopard2A5 

Going to wait for some feedback now. If you see things to change/improve, please do a PR on that branch.
Documentation hasn't been updated yet in case there are more changes coming like using traits.

**Comment by Keats** [comment]
And @lucab for #22

**Comment by theduke** [comment]
Sorry didn't get around to checking it out. 

I will this evening.

**Comment by Keats** [comment]
I'm updating the docs on master, I'll push in a bit

**Comment by Keats** [comment]
@theduke did you have time to look at it? I've seen that https://github.com/dtolnay/erased-serde got a new version so maybe it can used instead of serde_json

**Pull request merged**
