### PR TITLE
added message for required

### PR DESCRIPTION
**Pull request by pintariching**
When passing a message or code to the `required` attribute I get the following errors:
`unexpected list validator: "required"` and `no method named `validate` found for struct `can_specify_message_for_required::TestStruct` in the current scope`

I guess the `required` attribute doesn't take in any additional arguments? I'm still figuring out how to add that, here I just copied the tests from other attributes.

### CODE REVIEW

**Comment by Keats** [comment]
Looks that way indeed.

**Comment by pintariching** [comment]
Okay I think I managed to do it. It seems like the "required" validator was missing from two match statements.

**Comment by pintariching** [comment]
All the tests pass and you can now pass a message and a code to the required attribute. Should I close this pull request?

**Comment by Keats** [comment]
My bad, it's fine. Looks like we just need to change the pinned Rust version.

**Comment by pintariching** [comment]
To which version should the pinned version be changed?

**Comment by Keats** [comment]
To the first version that passes the CI, you can usually infer it by seeing the error and googling around.

**Comment by pintariching** [comment]
Okay it seems that the crate `hashbrown v0.12.1` is using the 2021 edition of rust, which is stabilized in rust 1.56.1. Should this be the pinned version?

**Comment by Keats** [comment]
Looks that way! Not sure how exactly we're depending on it, I'll have to double check.

**Comment by pintariching** [comment]
`indexmap v1.9.1` depends on `hashbrown v0.12.1`. Here's their [RELEASES.md](https://github.com/bluss/indexmap/blob/master/RELEASES.md) where they specify that the rust version should be at least 1.56.1 if you don't want to downgrade to `hashbrown v0.12.0`

**Review by Keats — APPROVED** [review]

**Pull request merged**
