### PR TITLE
Allow unsupported_field_type to be ignored

### PR DESCRIPTION
**Pull request by IniterWorker**
@Keats,

First of all, It is my first time dealing with macro in rust.

Maybe it is not the best way to do it. But, I created a new skip validator.
- Alternative is to ignore at compile time (inside the macro).

I would like some code review on:
- General skip purpose
- Necessary/Required tests

If you have any hint, you are welcome ;-)

Related to: https://github.com/Keats/validator/issues/182

### CODE REVIEW

**Comment by Keats** [comment]
It's not really a validator but more an attribute so I wouldn't go that way. I think it's fine to ignore all fields we cannot handle as long as they don't have a validator on them

**Comment by IniterWorker** [comment]
Are you asking to remove the abort?

https://github.com/Keats/validator/blob/f49848545ee048a4b69be68463ca4eb40725067f/validator_derive/src/lib.rs#L316

**Comment by Keats** [comment]
I think yes, according to https://github.com/Keats/validator/blob/f49848545ee048a4b69be68463ca4eb40725067f/validator_derive/src/lib.rs#L284-L285 it's only for the must_match so ideally we would only check fields with validators set

**Comment by IniterWorker** [comment]
@Keats, maybe something like that can be a beginning?

**Pull request merged**
