### PR TITLE
Update MSVR in README.md

### PR DESCRIPTION
**Pull request by fabienbellanger**
Update MSVR in `README.md`

### CODE REVIEW

**Comment by Keats** [comment]
I would be tempted to remove that line and just add a link to the line in the CI file (https://github.com/Keats/validator/blob/master/.github/workflows/ci.yml#L11) to avoid keeping it in multiple places. Thoughts?

**Comment by fabienbellanger** [comment]
Yes, this will prevent mistakes.
Why not add it to the `Cargo.toml` file by adding:
```toml
rust-version = "1.81"
```
?

**Comment by Keats** [comment]
The issue is that we can still forgot to update it in Cargo.toml except now Cargo will believe it

**Comment by fabienbellanger** [comment]
Yes, it seems impossible.

In `Cargo.toml`, add:
```
rust-version = "1.81"
```

In `ci.yml`, change by:
```
name: ci
on: [push, pull_request]

jobs:
  test_validator:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract Rust version from Cargo.toml
        run: |
          RUST_VERSION=$(sed -n 's/^rust-version = "\([^"]*\)"/\1/p' Cargo.toml)
          echo "MSRV: $RUST_VERSION"
          echo "RUST_VERSION=$RUST_VERSION" >> $GITHUB_ENV
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run: |
          cargo build --no-default-features
          cargo test --no-default-features
          cargo build --features unic --features derive --features card
          cargo test  --features unic --features derive --features card
  test_validator-nightly:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run: |
          cargo build --no-default-features
          cargo test --no-default-features
          cargo build --all-features
          cargo test --all-features
```

I don't test it on this projet yet, but on another projet, it works like a charm.

**Comment by Keats** [comment]
Let's try that then!

**Review by Keats — APPROVED** [review]
Nice, thanks

**Pull request merged**
