### PR TITLE
Derive Deserialize for ValidationErrors

### PR DESCRIPTION
**Pull request by Person-93**
Needed to change keys to String because the Deserializer can't provide &'static str

### CODE REVIEW

**Comment by Keats** [comment]
What is the usecase there? I'm expecting Validator to only ever serialize things

**Comment by Person-93** [comment]
@Keats I need it so that validation can be done on the server and error handling can be done on the client.

**Comment by Person-93** [comment]
I'm a bit confused by this error, is it a dependency that doesn't compile on the pinned toolchain?

**Comment by Keats** [comment]
> I'm a bit confused by this error, is it a dependency that doesn't compile on the pinned toolchain?

**Comment by Person-93** [comment]
Yes, it should work.
I was concerned that deserializing a `Cow<str>` would give it the lifetime of wherever it's derserialized from, but based on [this issue](https://github.com/serde-rs/serde/issues/1852) it looks like it does not and there are no plans to change that.
I'll fix it.

**Comment by Person-93** [comment]
> Can you rebase your PR?

I've deleted my fork, but I looked around and found [this commit](https://github.com/Keats/validator/tree/e0c9856a49ccf125b22d0fecba7d51ea9a4743aa) which looks like it has all my changes. Feel free to clone it and open your own PR.

**Pull request closed without merging**
